INSERT INTO test1 VALUES ('e');

SELECT SCOPE_IDENTITY();
SELECT @@IDENTITY;

SELECT * FROM test1;
SELECT * FROM test2;

CREATE TRIGGER trForInsert On test1 FOR INSERT
AS
BEGIN
    INSERT INTO test2 VALUES ('vvv');
END;
DELETE FROM test1 where ID = 7